# Rokha CLI Homebrew formula — REFERENCE TEMPLATE ONLY.
#
# ⚠ Do NOT hand-copy this to the tap. The published formula is generated by
# CI (`.github/workflows/cli-release.yml`, job `publish-homebrew`) on every
# `cli-v*` tag: it fetches the real per-platform sha256 sidecars from the GH
# release and pushes a filled-in formula to
# https://github.com/aetherBytes/homebrew-tap/Formula/rokha.rb.
#
# The `version` / `sha256` below are placeholders and will NOT match any real
# release — this copy exists to show the formula's shape, not to install from.
#
# Once released:
#   brew tap aetherBytes/tap
#   brew install rokha
# or one-shot:
#   brew install aetherBytes/tap/rokha

class Rokha < Formula
  desc "Rokha CLI — picks and shovels for the agentic economy"
  homepage "https://rokha.ai"
  version "1.0.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aetherBytes/rokha-sdk/releases/download/cli-v#{version}/ro-#{version}-aarch64-apple-darwin.tar.gz"
      sha256 "REPLACE_WITH_SHA256_DARWIN_ARM64"
    end
    on_intel do
      url "https://github.com/aetherBytes/rokha-sdk/releases/download/cli-v#{version}/ro-#{version}-x86_64-apple-darwin.tar.gz"
      sha256 "REPLACE_WITH_SHA256_DARWIN_X86_64"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aetherBytes/rokha-sdk/releases/download/cli-v#{version}/ro-#{version}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "REPLACE_WITH_SHA256_LINUX_ARM64"
    end
    on_intel do
      url "https://github.com/aetherBytes/rokha-sdk/releases/download/cli-v#{version}/ro-#{version}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "REPLACE_WITH_SHA256_LINUX_X86_64"
    end
  end

  def install
    bin.install "ro"
  end

  test do
    assert_match(/ro #{version}/, shell_output("#{bin}/ro version"))
  end
end
