use std::path::PathBuf;
use std::process::{Command, Stdio};

use crate::credentials;

const EMBEDDED_COMPOSE: &str = include_str!("compose.yml");
const PROJECT_NAME: &str = "rokha";
const DEFAULT_REMOTE_LLM_PROXY: &str = "https://erebus.rokha.ai/api/v1/llm/proxy";

fn rokha_home() -> PathBuf {
    dirs::home_dir()
        .unwrap_or_else(|| PathBuf::from("."))
        .join(".rokha")
}

fn compose_path() -> PathBuf {
    let dir = rokha_home();
    let _ = std::fs::create_dir_all(&dir);
    dir.join("compose.yml")
}

fn env_file_path() -> PathBuf {
    rokha_home().join("env")
}

fn write_compose() -> std::io::Result<PathBuf> {
    let path = compose_path();
    std::fs::write(&path, EMBEDDED_COMPOSE)?;
    Ok(path)
}

/// Best-effort: on first run, drop a default ~/.rokha/env with safe local-dev
/// secrets. We deliberately don't overwrite an existing file.
fn ensure_env_file() -> std::io::Result<PathBuf> {
    let path = env_file_path();
    if path.exists() {
        return Ok(path);
    }
    let _ = std::fs::create_dir_all(rokha_home());
    let body = concat!(
        "# Rokha local-stack environment. Generated by `ro up` on first run.\n",
        "# Override any value here, then re-run `ro up`.\n",
        "\n",
        "# Postgres password used by the embedded compose.\n",
        "POSTGRES_PASSWORD=rokha_dev\n",
        "\n",
        "# Erebus secrets. CHANGE THESE BEFORE EXPOSING THE STACK BEYOND LOCALHOST.\n",
        "JWT_SECRET=dev-only-jwt-secret-please-override\n",
        "ENCRYPTION_MASTER_KEY=dev-only-encryption-key-32-bytes!\n",
        "\n",
        "# v0.3 transitional. v0.4 will route LLM through your Rokha account\n",
        "# (`ro login`). Until then, set this to use the local agent.\n",
        "# ANTHROPIC_KEY_ROKHA_AGENT=\n",
        "\n",
        "# Pin to a specific service image release, or \"latest\".\n",
        "ROKHA_IMAGE_TAG=latest\n",
    );
    std::fs::write(&path, body)?;
    Ok(path)
}

/// Pre-flight: docker on PATH + daemon reachable.
fn preflight() -> Result<(), String> {
    if which::which("docker").is_err() {
        return Err(concat!(
            "docker not found on PATH.\n\n",
            "ro up needs Docker (or a Docker-compatible runtime). Install one of:\n",
            "  macOS:   Docker Desktop, Colima (brew install colima), or OrbStack\n",
            "  Linux:   docker-ce (https://docs.docker.com/engine/install/)\n",
            "\nIf Docker is installed, ensure `docker` is on your PATH."
        )
        .to_string());
    }
    let info = Command::new("docker")
        .arg("info")
        .stdout(Stdio::null())
        .stderr(Stdio::null())
        .status();
    match info {
        Ok(s) if s.success() => Ok(()),
        _ => Err(concat!(
            "docker daemon is not running.\n\n",
            "Start Docker and try again:\n",
            "  Docker Desktop:  open the app\n",
            "  Colima:          colima start\n",
            "  Linux:           sudo systemctl start docker"
        )
        .to_string()),
    }
}

fn run_compose(args: &[&str]) -> i32 {
    let path = match write_compose() {
        Ok(p) => p,
        Err(e) => {
            eprintln!("Could not write embedded compose: {}", e);
            return 1;
        }
    };
    let mut cmd = Command::new("docker");
    cmd.args(["compose", "-f"])
        .arg(&path)
        .args(["-p", PROJECT_NAME]);

    if let Ok(env_path) = ensure_env_file() {
        cmd.args(["--env-file"]).arg(&env_path);
    }

    // Propagate ro login → agents container. If the user is logged in,
    // we hand the JWT to the container via the docker-compose process
    // env, which substitutes `${ROKHA_LLM_JWT}` in compose.yml. If not
    // logged in, the variable is unset and the container starts in
    // "needs credentials" mode (visible via `ro status`).
    if let Some(creds) = credentials::load() {
        cmd.env("ROKHA_LLM_JWT", creds.jwt);
        // Default to the cloud proxy unless the user has overridden it.
        // We don't overwrite an explicit env / .rokha/env value here.
        if std::env::var("ROKHA_LLM_PROXY_URL").is_err() {
            cmd.env("ROKHA_LLM_PROXY_URL", DEFAULT_REMOTE_LLM_PROXY);
        }
    }

    cmd.args(args);
    match cmd.status() {
        Ok(s) => s.code().unwrap_or(0),
        Err(e) => {
            eprintln!("docker compose failed to launch: {}", e);
            1
        }
    }
}

pub async fn up() -> i32 {
    if let Err(msg) = preflight() {
        eprintln!("{}", msg);
        return 1;
    }

    let env_path = ensure_env_file().ok();
    if let Some(p) = &env_path {
        println!("env: {}", p.display());
    }

    match credentials::load() {
        Some(c) => println!("auth: signed in as {} (jwt → agents container)", c.identity.identity),
        None => println!("auth: not logged in — agents container will start in 'needs credentials' mode. Run `ro login` first to chat without a local Anthropic key."),
    }

    println!("Starting Rokha local stack (postgres + redis + erebus + agents + harnesses + protocols)...");
    let code = run_compose(&["up", "-d"]);
    if code != 0 {
        eprintln!();
        eprintln!("Stack failed to start. If pulls failed, the service images may not");
        eprintln!("be published yet. Set ROKHA_IMAGE_TAG=<existing-tag> in ~/.rokha/env,");
        eprintln!("or build locally from a Rokha checkout (`just dev`).");
        return code;
    }
    println!();
    println!("✓ Stack ready");
    println!("    erebus           http://localhost:3000");
    println!("    rokha-agents     http://localhost:9003");
    println!("    rokha-harnesses  http://localhost:9004");
    println!("    rokha-protocols  http://localhost:8001");
    println!("    postgres-erebus  localhost:5440");
    println!("    postgres-agents  localhost:5441");
    println!("    redis            localhost:6379");
    println!();
    println!("Run `ro status` to verify each service is healthy.");
    println!("Run `ro logs <service>` to follow logs.");
    println!();
    println!("v0.3 transitional: rokha-agents needs an LLM key. Either set");
    println!("ANTHROPIC_KEY_ROKHA_AGENT in ~/.rokha/env, or wait for v0.4 which");
    println!("routes LLM calls through your Rokha account (`ro login`).");
    0
}

pub async fn down() -> i32 {
    if let Err(msg) = preflight() {
        eprintln!("{}", msg);
        return 1;
    }
    println!("Stopping Rokha local stack...");
    run_compose(&["down"])
}

pub async fn logs(service: Option<&str>) -> i32 {
    if let Err(msg) = preflight() {
        eprintln!("{}", msg);
        return 1;
    }
    let mut args: Vec<&str> = vec!["logs", "-f"];
    if let Some(s) = service {
        args.push(s);
    }
    run_compose(&args)
}
